action: ??? # train or test
name: ??? # name of the experiment needed for the logs
modality: ["RGB"] # modality used
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: null # directory containing all the models
load_feat: False
experiment_dir_name: last

train:
  num_iter: 5000 # number of training iterations with total_batch size
  lr_steps: 3000 # steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  num_clips:
    RGB: 1
    EMG: 1
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
    EMG: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 16
    EMG: 100
  stride:
    RGB: 1
    EMG: 1

test:
  num_clips:
    RGB: 5
    EMG: 1
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True
    EMG: True
  num_frames_per_clip: # number of frames adopted in test for each modality
    RGB: 16
    EMG: 100
  stride:
    RGB: 1
    EMG: 1

dataset:
  annotations_path: ??? # path for the annotations data
  workers: 4 # number of workers for the dataloader
  resolution: 224 # input resolution to the model
  RGB:
    data_path: ??? # path to RGB data
    tmpl: "frames_{:010d}.jpg" # format of RGB filenames
    features_name: test_feat_kinetics

# these are the action recognition models for each modality
models:
  RGB:
    model: I3D
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
    weight_i3d_rgb: './pretrained_i3d/rgb_imagenet.pt'
