action: train # train or test
name: emg_train # name of the experiment needed for the logs
modality: ["EMG"] # modality used

train:
  num_clips: 1
  dense_sampling: 
    EMGl: True
    EMGr: True
  num_frames_per_clip: 
    EMG: 100
  stride:
    EMG: 1

test:
  num_clips: 5
  dense_sampling: 
    EMGl: True
    EMGr: True
  num_frames_per_clip: 
    EMG: 100
  stride:
    EMG: 1

dataset:
  annotations_path: data/ActionNet # path for the annotations data
  workers: 4 # number of workers for the dataloader
  resolution: 224 # input resolution to the model
  RGB:
    data_path: Volumes/Mac/AML/frames

# these are the action recognition models for each modality
models:
  RGB:
    model: I3D
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
    weight_i3d_rgb: './pretrained_i3d/rgb_imagenet.pt'
  EMG:
    model: ActionNet
    hidden_size: 50
    dropout: 0.2
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
    fs: 160
    cutoff: 5
    num_channels: 16
    normalization: False
