action: save # train or test
name: saved_feat_I3D
split: train

save:
  num_clips: 1
  dense_sampling:
    RGB: True
  num_frames_per_clip:
    RGB: 16
  stride:
    RGB: 2


dataset:
  annotations_path: data/final
  workers: 4
  resolution: 224
  RGB:
    data_path: data/frames
    tmpl: "frame_{:010d}.jpg"
  Event:
    rgb4e: 6

# these are the action recognition models for each modality
models:
  RGB:
    model: I3D
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
    weight_i3d_rgb: './pretrained_i3d/rgb_imagenet.pt'


