action: train # train or test
name: midlevel_train # name of the experiment needed for the logs
modality: ["MIDLEVEL"] # modality used
load_feat:
  RGB: True
  EMG: False
multimodal: True

train:
  num_clips: 1
  eval_freq: 50
  dense_sampling: 
    EMG: False
    RGB: False
  num_frames_per_clip: 
    EMG: 100
    RGB: 10
  stride:
    EMG: 2
    RGB: 2

test:
  num_clips: 5
  dense_sampling: 
    EMG: False
    RGB: False
  num_frames_per_clip: 
    EMG: 100
    RGB: 10
  stride:
    EMG: 2
    RGB: 2

dataset:
  annotations_path: data/final_10x20 # path for the annotations data
  workers: 4 # number of workers for the dataloader
  resolution: 224 # input resolution to the model
  RGB:
    data_path: data/frames

# these are the action recognition models for each modality
models:
  RGB:
    model: MLP_Classifier_2
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  EMG:
    model: ActionNet
    hidden_size: 50
    dropout: 0.2
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.1
    sgd_momentum: 0.9
    weight_decay: 1e-7
    fs: 160
    cutoff: 5
    num_channels: 16
    normalization: False
  MIDLEVEL:
    model: MidlevelActionNet
    emg_feature_size: 1024
    rgb_feature_size: 1024
    dropout: 0.25
    lr_steps: 3000
    lr: 0.1
    sgd_momentum: 0.9
    weight_decay: 1e-7
    hidden_size: 512

